---
- name: Copy group members file
  hosts: all
  tasks:
    - name: Create group members file from template
      template:
        src: ../template/group_members.txt.j2
        dest: /tmp/group_members.txt

    - name: Display the content of the copied file
      command: cat /tmp/group_members.txt
      register: file_content

    - name: Show the file content
      debug:
        var: file_content.stdout_lines